# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-29 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_thread_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="country",
            field=models.CharField(blank=True, default=b"United States", max_length=63),
        ),
    ]
