# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_account_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="congress_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="govtrack_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="source",
            field=models.CharField(
                choices=[(b"sunlight", b"sunlight"), (b"propublica", b"propublica")],
                default=b"sunlight",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="civi",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="civis",
                to="api.Account",
            ),
        ),
        migrations.AlterField(
            model_name="civi",
            name="thread",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="civis",
                to="api.Thread",
            ),
        ),
    ]
