# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190304_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='civi',
            name='linked_bills',
            field=models.ManyToManyField(related_name='bills', to='api.Bill'),
        ),
    ]
