# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


def remove_reps(apps, schema_editor):
    Representative = apps.get_model("api", "Representative")
    Representative.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_civi_linked_bills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="representative",
            old_name="bioguideID",
            new_name="bioguide_id",
        ),
        migrations.RenameField(
            model_name="representative",
            old_name="term_end",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="representative",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="representative",
            old_name="term_start",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="about_me",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="level",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="official_full_name",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="senate_class",
        ),
        migrations.AddField(
            model_name="representative",
            name="chamber",
            field=models.CharField(
                choices=[(b"house", b"House"), (b"senate", b"Senate")],
                default="senate",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(remove_reps),
    ]
