# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_auto_20190418_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="is_voted_data_updated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="representative",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="representative",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vote",
            name="bill",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.Bill"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vote",
            name="representative",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Representative",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set([("bill", "representative")]),
        ),
    ]
