# Generated by Django 2.2.16 on 2021-05-26 13:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('api', '0035_auto_20210526_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='civi',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='civi',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
