# Generated by Django 3.2.6 on 2021-08-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210527_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='beta_access',
        ),
    ]
