# Generated by Django 3.2.6 on 2021-08-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_account_beta_access'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
