# Generated by Django 3.2.7 on 2021-09-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account'),
        ('api', '0040_delete_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='civi',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='civis', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='rebuttal',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
