# Generated by Django 3.2.7 on 2021-09-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('accounts', '0005_alter_profile_categories'),
        ('api', '0041_auto_20210906_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='account',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='civi',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='thread',
        ),
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
