# Generated by Django 3.2.7 on 2021-09-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20210927_0925'),
        ('api', '0042_auto_20210928_1413'),
    ]

    operations = [
    ]
