# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170615_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civi',
            name='links',
        ),
    ]
