<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-09-28 08:43
=======
# Generated by Django 3.2.7 on 2021-09-27 09:25
>>>>>>> f693e3c878920b2ff58c282b4f88f507b61bf985

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
