# Generated by Django 3.2.7 on 2021-09-28 11:35

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "__first__"),
        ("categories", "0001_initial"),
        ("taggit", "0003_taggeditem_add_unique_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Civi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.CharField(max_length=1023)),
                (
                    "c_type",
                    models.CharField(
                        choices=[
                            ("problem", "Problem"),
                            ("cause", "Cause"),
                            ("solution", "Solution"),
                            ("response", "Response"),
                            ("rebuttal", "Rebuttal"),
                        ],
                        default="problem",
                        max_length=31,
                    ),
                ),
                ("votes_vneg", models.IntegerField(default=0)),
                ("votes_neg", models.IntegerField(default=0)),
                ("votes_neutral", models.IntegerField(default=0)),
                ("votes_pos", models.IntegerField(default=0)),
                ("votes_vpos", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="civis",
                        to="accounts.profile",
                    ),
                ),
                (
                    "linked_civis",
                    models.ManyToManyField(
                        related_name="_threads_civi_linked_civis_+", to="threads.Civi"
                    ),
                ),
                (
                    "response_civis",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="threads.Civi",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=511)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rationale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("body", models.TextField(max_length=4095)),
                ("votes_vneg", models.IntegerField(default=0)),
                ("votes_neg", models.IntegerField(default=0)),
                ("votes_neutral", models.IntegerField(default=0)),
                ("votes_pos", models.IntegerField(default=0)),
                ("votes_vpos", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("summary", models.CharField(max_length=4095)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=common.utils.PathAndRename("")
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("federal", "Federal"), ("state", "State")],
                        default="federal",
                        max_length=31,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("DC", "District of Columbia"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        max_length=2,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("is_draft", models.BooleanField(default=True)),
                ("num_views", models.IntegerField(default=0)),
                ("num_civis", models.IntegerField(default=0)),
                ("num_solutions", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.profile",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="categories.category",
                    ),
                ),
                ("facts", models.ManyToManyField(to="threads.Fact")),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("body", models.TextField(max_length=2047)),
                ("votes_vneg", models.IntegerField(default=0)),
                ("votes_neg", models.IntegerField(default=0)),
                ("votes_neutral", models.IntegerField(default=0)),
                ("votes_pos", models.IntegerField(default=0)),
                ("votes_vpos", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.profile",
                    ),
                ),
                (
                    "civi",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="threads.Civi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rebuttal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=1023)),
                ("votes_vneg", models.IntegerField(default=0)),
                ("votes_neg", models.IntegerField(default=0)),
                ("votes_neutral", models.IntegerField(default=0)),
                ("votes_pos", models.IntegerField(default=0)),
                ("votes_vpos", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.profile",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="threads.response",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CiviImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=common.utils.PathAndRename("")
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "civi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="threads.Civi",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="civi",
            name="thread",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="civis",
                to="threads.thread",
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("vote_vneg", "Vote Strongly Disagree"),
                            ("vote_neg", "Vote Disagree"),
                            ("vote_neutral", "Vote Neutral"),
                            ("vote_pos", "Vote Agree"),
                            ("vote_vpos", "Vote Strongly Agree"),
                            ("favorite", "Favor a Civi"),
                        ],
                        max_length=255,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.profile",
                    ),
                ),
                (
                    "civi",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="threads.Civi",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="threads.thread",
                    ),
                ),
            ],
        ),
    ]
