# Generated by Django 3.2.7 on 2021-10-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='level',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='state',
        ),
    ]
