# Generated by Django 3.2.7 on 2021-10-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20211006_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civi',
            name='response_civis',
        ),
        migrations.AlterField(
            model_name='civi',
            name='linked_civis',
            field=models.ManyToManyField(blank=True, related_name='_threads_civi_linked_civis_+', to='threads.Civi'),
        ),
    ]
