# Generated by Django 4.1.2 on 2024-10-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0007_alter_activity_civi_alter_activity_thread_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CiviLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("causes", "Causes"),
                            ("solves", "Solves"),
                            ("related", "Related"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "from_civi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="threads.civi",
                    ),
                ),
                (
                    "to_civi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="threads.civi",
                    ),
                ),
            ],
        ),
    ]
