PROPUBLICA_CORRECT_RESPONSE = {
    u"status": u"OK",
    u"results": [
        {
            u"bills": [
                {
                    u"senate_passage": u"2019-01-25",
                    u"sponsor_name": u"Lucille Roybal-Allard",
                    u"number": u"H.J.RES.31",
                    u"house_passage": u"2019-01-24",
                    u"sponsor_id": u"R000486",
                    u"sponsor_party": u"D",
                    u"summary": u"This joint resolution provides continuing FY2019 appropriations for the Department of Homeland Security (DHS) through the earlier of February 15, 2019, or the enactment of the applicable appropriations legislation.  It is known as a continuing resolution (CR) and ends the partial DHS shutdown that began on December 22, 2018, because the existing CR expired and the FY2019 DHS appropriations bill has not been enacted.  Additionally, the CR has the effect of extending through February 15, 2019, several immigration programs and authorities that were extended in prior CRs and expired on December 21, 2018. ",
                    u"cosponsors_by_party": {},
                    u"vetoed": None,
                    u"title": u"Making further continuing appropriations for the Department of Homeland Security for fiscal year 2019, and for other purposes.",
                    u"summary_short": u"This joint resolution provides continuing FY2019 appropriations for the Department of Homeland Security (DHS) through the earlier of February 15, 2019, or the enactment of the applicable appropriations legislation.  It is known as a continuing resolution (CR) and ends the partial DHS shutdown that began on December 22, 2018, because the existing CR expired and the FY2019 DHS appropriations bill has not been enacted.  Additionally, the CR has the effect of extending through February 15, 2019, ...",
                    u"last_vote": u"2019-02-14",
                    u"sponsor_state": u"CA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-joint-resolution/31",
                    u"bill_type": u"hjres",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hjres31enr/pdf/BILLS-116hjres31enr.pdf",
                    u"primary_subject": u"Economics and Public Finance",
                    u"active": True,
                    u"committees": u"House Appropriations Committee",
                    u"enacted": u"2019-02-15",
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hjres31.json",
                    u"latest_major_action": u"Became Public Law No: 116-6.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/R000486.json",
                    u"committee_codes": [u"HSAP"],
                    u"short_title": u"Consolidated Appropriations Act, 2019",
                    u"introduced_date": u"2019-01-22",
                    u"latest_major_action_date": u"2019-02-15",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hjres31",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hjres31",
                    u"cosponsors": 0,
                    u"bill_id": u"hjres31-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Ron Wyden",
                    u"number": u"S.515",
                    u"house_passage": None,
                    u"sponsor_id": u"W000779",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"D": 44, u"ID": 2},
                    u"vetoed": None,
                    u"title": u"A bill to amend the Internal Revenue Code of 1986 to clarify that all provisions shall apply to legally married same-sex couples in the same manner as other married couples, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"OR",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/senate-bill/515",
                    u"bill_type": u"s",
                    u"gpo_pdf_uri": None,
                    u"primary_subject": u"",
                    u"active": False,
                    u"committees": u"Senate Finance Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/s515.json",
                    u"latest_major_action": u"Read twice and referred to the Committee on Finance.",
                    u"sponsor_title": u"Sen.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/W000779.json",
                    u"committee_codes": [u"SSFI"],
                    u"short_title": u"A bill to amend the Internal Revenue Code of 1986 to clarify that all provisions shall apply to legally married same-sex couples in the same manner as other married couples, and for other purposes.",
                    u"introduced_date": u"2019-02-14",
                    u"latest_major_action_date": u"2019-02-14",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/s515",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"s515",
                    u"cosponsors": 46,
                    u"bill_id": u"s515-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Andy Levin",
                    u"number": u"H.R.1244",
                    u"house_passage": None,
                    u"sponsor_id": u"L000592",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"D": 74},
                    u"vetoed": None,
                    u"title": u"To amend the Internal Revenue Code of 1986 to clarify that all provisions shall apply to legally married same-sex couples in the same manner as other married couples, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"MI",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/1244",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": None,
                    u"primary_subject": u"",
                    u"active": False,
                    u"committees": u"House Ways and Means Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr1244.json",
                    u"latest_major_action": u"Referred to the House Committee on Ways and Means.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/L000592.json",
                    u"committee_codes": [u"HSWM"],
                    u"short_title": u"To amend the Internal Revenue Code of 1986 to clarify that all provisions shall apply to legally married same-sex couples in the same manner as other married couples, and for other purposes.",
                    u"introduced_date": u"2019-02-14",
                    u"latest_major_action_date": u"2019-02-14",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr1244",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr1244",
                    u"cosponsors": 74,
                    u"bill_id": u"hr1244-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Judy Chu",
                    u"number": u"H.R.810",
                    u"house_passage": None,
                    u"sponsor_id": u"C001080",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"D": 69},
                    u"vetoed": None,
                    u"title": u"To block the implementation of certain presidential actions that restrict individuals from certain countries from entering the United States.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"CA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/810",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr810ih/pdf/BILLS-116hr810ih.pdf",
                    u"primary_subject": u"Immigration",
                    u"active": False,
                    u"committees": u"House Homeland Security Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr810.json",
                    u"latest_major_action": u"Referred to the Subcommittee on Border Security, Facilitation, and Operations.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/C001080.json",
                    u"committee_codes": [u"HSJU"],
                    u"short_title": u"To block the implementation of certain presidential actions that restrict individuals from certain countries from entering the United States.",
                    u"introduced_date": u"2019-01-28",
                    u"latest_major_action_date": u"2019-02-13",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr810",
                    u"subcommittee_codes": [u"HSHM11"],
                    u"bill_slug": u"hr810",
                    u"cosponsors": 69,
                    u"bill_id": u"hr810-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Dianne Feinstein",
                    u"number": u"S.RES.36",
                    u"house_passage": None,
                    u"sponsor_id": u"F000062",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 5, u"D": 7},
                    u"vetoed": None,
                    u"title": u"A resolution supporting the observation of National Trafficking and Modern Slavery Prevention Month during the period beginning on January 1, 2019, and ending on February 1, 2019, to raise awareness of, and opposition to, human trafficking and modern slavery.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"CA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/senate-resolution/36",
                    u"bill_type": u"sres",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116sres36ats/pdf/BILLS-116sres36ats.pdf",
                    u"primary_subject": u"Crime and Law Enforcement",
                    u"active": True,
                    u"committees": u"Senate Judiciary Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/sres36.json",
                    u"latest_major_action": u"Resolution agreed to in Senate without amendment and with a preamble by Unanimous Consent.",
                    u"sponsor_title": u"Sen.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/F000062.json",
                    u"committee_codes": [u"SSJU"],
                    u"short_title": u"A resolution supporting the observation of National Trafficking and Modern Slavery Prevention Month during the period beginning on January 1, 2019, and ending on February 1, 2019, to raise awareness of, and opposition to, human trafficking and modern slav",
                    u"introduced_date": u"2019-01-31",
                    u"latest_major_action_date": u"2019-02-12",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/sres36",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"sres36",
                    u"cosponsors": 12,
                    u"bill_id": u"sres36-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Julia Brownley",
                    u"number": u"H.R.840",
                    u"house_passage": u"2019-02-08",
                    u"sponsor_id": u"B001285",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"D": 22},
                    u"vetoed": None,
                    u"title": u"To amend title 38, United States Code, to direct the Secretary of Veterans Affairs to provide child care assistance to veterans receiving certain medical services provided by the Department of Veterans Affairs.",
                    u"summary_short": u"",
                    u"last_vote": u"2019-02-08",
                    u"sponsor_state": u"CA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/840",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr840rfs/pdf/BILLS-116hr840rfs.pdf",
                    u"primary_subject": u"Armed Forces and National Security",
                    u"active": True,
                    u"committees": u"Senate Veterans&#39; Affairs Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr840.json",
                    u"latest_major_action": u"Received in the Senate and Read twice and referred to the Committee on Veterans' Affairs.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/B001285.json",
                    u"committee_codes": [u"SSVA", u"HSVR"],
                    u"short_title": u"Veterans' Access to Child Care Act",
                    u"introduced_date": u"2019-01-29",
                    u"latest_major_action_date": u"2019-02-11",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr840",
                    u"subcommittee_codes": [u"HSVR03"],
                    u"bill_slug": u"hr840",
                    u"cosponsors": 22,
                    u"bill_id": u"hr840-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Karen Bass",
                    u"number": u"H.R.507",
                    u"house_passage": u"2019-02-07",
                    u"sponsor_id": u"B001270",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 3, u"D": 4},
                    u"vetoed": None,
                    u"title": u"To direct the Attorney General to study issues relating to human trafficking, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": u"2019-02-07",
                    u"sponsor_state": u"CA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/507",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr507rfs/pdf/BILLS-116hr507rfs.pdf",
                    u"primary_subject": u"Crime and Law Enforcement",
                    u"active": True,
                    u"committees": u"Senate Judiciary Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr507.json",
                    u"latest_major_action": u"Received in the Senate and Read twice and referred to the Committee on the Judiciary.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/B001270.json",
                    u"committee_codes": [u"SSJU", u"HSJU"],
                    u"short_title": u"Put Trafficking Victims First Act of 2019",
                    u"introduced_date": u"2019-01-11",
                    u"latest_major_action_date": u"2019-02-11",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr507",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr507",
                    u"cosponsors": 7,
                    u"bill_id": u"hr507-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Christopher H. Smith",
                    u"number": u"H.R.1100",
                    u"house_passage": None,
                    u"sponsor_id": u"S000522",
                    u"sponsor_party": u"R",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"D": 1},
                    u"vetoed": None,
                    u"title": u"To direct the Attorney General to make grants to States that have in place laws that expand the protections offered to victims of sex offenses who are not in a familiar or dating relationship with the perpetrators of such offenses.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"NJ",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/1100",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr1100ih/pdf/BILLS-116hr1100ih.pdf",
                    u"primary_subject": u"",
                    u"active": False,
                    u"committees": u"House Judiciary Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr1100.json",
                    u"latest_major_action": u"Referred to the House Committee on the Judiciary.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/S000522.json",
                    u"committee_codes": [u"HSJU"],
                    u"short_title": u"To direct the Attorney General to make grants to States that have in place laws that expand the protections offered to victims of sex offenses who are not in a familiar or dating relationship with the perpetrators of such offenses.",
                    u"introduced_date": u"2019-02-07",
                    u"latest_major_action_date": u"2019-02-07",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr1100",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr1100",
                    u"cosponsors": 1,
                    u"bill_id": u"hr1100-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Catherine Cortez Masto",
                    u"number": u"S.410",
                    u"house_passage": None,
                    u"sponsor_id": u"C001113",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 1},
                    u"vetoed": None,
                    u"title": u"A bill to require the Comptroller General of the United States to carry out a study on how virtual currencies and online marketplaces are used to buy, sell, or facilitate the financing of goods or services associated with sex trafficking or drug trafficking, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"NV",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/senate-bill/410",
                    u"bill_type": u"s",
                    u"gpo_pdf_uri": None,
                    u"primary_subject": u"",
                    u"active": False,
                    u"committees": u"Senate Banking, Housing, and Urban Affairs Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/s410.json",
                    u"latest_major_action": u"Read twice and referred to the Committee on Banking, Housing, and Urban Affairs.",
                    u"sponsor_title": u"Sen.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/C001113.json",
                    u"committee_codes": [u"SSBK"],
                    u"short_title": u"A bill to require the Comptroller General of the United States to carry out a study on how virtual currencies and online marketplaces are used to buy, sell, or facilitate the financing of goods or services associated with sex trafficking or drug trafficki",
                    u"introduced_date": u"2019-02-07",
                    u"latest_major_action_date": u"2019-02-07",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/s410",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"s410",
                    u"cosponsors": 1,
                    u"bill_id": u"s410-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Jackie Speier",
                    u"number": u"H.R.1032",
                    u"house_passage": None,
                    u"sponsor_id": u"S001175",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 1, u"D": 3},
                    u"vetoed": None,
                    u"title": u"To provide for the retention and service of transgender individuals in the Armed Forces.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"CA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/1032",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": None,
                    u"primary_subject": u"",
                    u"active": False,
                    u"committees": u"House Armed Services Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr1032.json",
                    u"latest_major_action": u"Referred to the House Committee on Armed Services.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/S001175.json",
                    u"committee_codes": [u"HSAS"],
                    u"short_title": u"To provide for the retention and service of transgender individuals in the Armed Forces.",
                    u"introduced_date": u"2019-02-07",
                    u"latest_major_action_date": u"2019-02-07",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr1032",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr1032",
                    u"cosponsors": 4,
                    u"bill_id": u"hr1032-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Dina Titus",
                    u"number": u"H.R.1030",
                    u"house_passage": None,
                    u"sponsor_id": u"T000468",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 1, u"D": 21},
                    u"vetoed": None,
                    u"title": u'To amend title 38, United States Code, to amend the definition of the term "spouse" to recognize new State definitions of such term for the purpose of the laws administered by the Secretary of Veterans Affairs, and for other purposes.',
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"NV",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/1030",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr1030ih/pdf/BILLS-116hr1030ih.pdf",
                    u"primary_subject": u"Armed Forces and National Security",
                    u"active": False,
                    u"committees": u"House Veterans&#39; Affairs Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr1030.json",
                    u"latest_major_action": u"Referred to the House Committee on Veterans' Affairs.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/T000468.json",
                    u"committee_codes": [u"HSVR"],
                    u"short_title": u"Veteran Spouses Equal Treatment Act",
                    u"introduced_date": u"2019-02-06",
                    u"latest_major_action_date": u"2019-02-06",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr1030",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr1030",
                    u"cosponsors": 22,
                    u"bill_id": u"hr1030-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Suzanne Bonamici",
                    u"number": u"H.R.989",
                    u"house_passage": None,
                    u"sponsor_id": u"B001278",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 5, u"D": 5},
                    u"vetoed": None,
                    u"title": u"To promote registered apprenticeships and other work-based learning programs for small and medium-sized businesses within in-demand industry sectors, through the establishment and support of industry or sector partnerships.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"OR",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/989",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr989ih/pdf/BILLS-116hr989ih.pdf",
                    u"primary_subject": u"Labor and Employment",
                    u"active": False,
                    u"committees": u"House Judiciary Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr989.json",
                    u"latest_major_action": u"Referred to the Committee on Education and Labor, and in addition to the Committee on the Judiciary, for a period to be subsequently determined by the Speaker, in each case for consideration of such provisions as fall within the jurisdiction of the committee concerned.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/B001278.json",
                    u"committee_codes": [u"HSED"],
                    u"short_title": u"PARTNERS Act",
                    u"introduced_date": u"2019-02-06",
                    u"latest_major_action_date": u"2019-02-06",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr989",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr989",
                    u"cosponsors": 10,
                    u"bill_id": u"hr989-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Frederica Wilson",
                    u"number": u"H.R.1000",
                    u"house_passage": None,
                    u"sponsor_id": u"W000808",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {},
                    u"vetoed": None,
                    u"title": u"To establish a National Full Employment Trust Fund to create employment opportunities for the unemployed, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"FL",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/1000",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr1000ih/pdf/BILLS-116hr1000ih.pdf",
                    u"primary_subject": u"Labor and Employment",
                    u"active": False,
                    u"committees": u"House Ways and Means Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr1000.json",
                    u"latest_major_action": u"Referred to the Committee on Education and Labor, and in addition to the Committee on Ways and Means, for a period to be subsequently determined by the Speaker, in each case for consideration of such provisions as fall within the jurisdiction of the committee concerned.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/W000808.json",
                    u"committee_codes": [u"HSED"],
                    u"short_title": u"Jobs for All Act",
                    u"introduced_date": u"2019-02-06",
                    u"latest_major_action_date": u"2019-02-06",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr1000",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr1000",
                    u"cosponsors": 0,
                    u"bill_id": u"hr1000-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Debbie Dingell",
                    u"number": u"H.R.973",
                    u"house_passage": None,
                    u"sponsor_id": u"D000624",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 6, u"D": 7},
                    u"vetoed": None,
                    u"title": u"To amend the Public Health Service Act to provide for additional programs funded by grants to strengthen the healthcare system's response to domestic violence, dating violence, sexual assault, and stalking, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"MI",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/973",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr973ih/pdf/BILLS-116hr973ih.pdf",
                    u"primary_subject": u"Health",
                    u"active": False,
                    u"committees": u"House Energy and Commerce Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr973.json",
                    u"latest_major_action": u"Referred to the House Committee on Energy and Commerce.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/D000624.json",
                    u"committee_codes": [u"HSIF"],
                    u"short_title": u"Violence Against Women Health Act of 2019",
                    u"introduced_date": u"2019-02-05",
                    u"latest_major_action_date": u"2019-02-05",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr973",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr973",
                    u"cosponsors": 13,
                    u"bill_id": u"hr973-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Patty Murray",
                    u"number": u"S.319",
                    u"house_passage": None,
                    u"sponsor_id": u"M001111",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"D": 5},
                    u"vetoed": None,
                    u"title": u"A bill to improve the reproductive assistance provided by the Department of Defense and the Department of Veterans Affairs to severely wounded, ill, or injured members of the Armed Forces, veterans, and their spouses or partners, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"WA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/senate-bill/319",
                    u"bill_type": u"s",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116s319is/pdf/BILLS-116s319is.pdf",
                    u"primary_subject": u"Armed Forces and National Security",
                    u"active": False,
                    u"committees": u"Senate Veterans&#39; Affairs Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/s319.json",
                    u"latest_major_action": u"Read twice and referred to the Committee on Veterans' Affairs.",
                    u"sponsor_title": u"Sen.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/M001111.json",
                    u"committee_codes": [u"SSVA"],
                    u"short_title": u"Women Veterans and Families Health Services Act of 2019",
                    u"introduced_date": u"2019-02-04",
                    u"latest_major_action_date": u"2019-02-04",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/s319",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"s319",
                    u"cosponsors": 5,
                    u"bill_id": u"s319-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Rick Larsen",
                    u"number": u"H.R.955",
                    u"house_passage": None,
                    u"sponsor_id": u"L000560",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"D": 15},
                    u"vetoed": None,
                    u"title": u"To improve the reproductive assistance provided by the Department of Defense and the Department of Veterans Affairs to severely wounded, ill, or injured members of the Armed Forces, veterans, and their spouses or partners, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"WA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/955",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr955ih/pdf/BILLS-116hr955ih.pdf",
                    u"primary_subject": u"Armed Forces and National Security",
                    u"active": False,
                    u"committees": u"House Armed Services Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr955.json",
                    u"latest_major_action": u"Referred to the Committee on Veterans' Affairs, and in addition to the Committee on Armed Services, for a period to be subsequently determined by the Speaker, in each case for consideration of such provisions as fall within the jurisdiction of the committee concerned.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/L000560.json",
                    u"committee_codes": [u"HSVR"],
                    u"short_title": u"Women Veterans and Families Health Services Act of 2019",
                    u"introduced_date": u"2019-02-04",
                    u"latest_major_action_date": u"2019-02-04",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr955",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr955",
                    u"cosponsors": 15,
                    u"bill_id": u"hr955-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Tina Smith",
                    u"number": u"S.288",
                    u"house_passage": None,
                    u"sponsor_id": u"S001203",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 1, u"D": 1},
                    u"vetoed": None,
                    u"title": u"A bill to amend the Indian Civil Rights Act of 1968 to extend the jurisdiction of tribal courts to cover crimes involving sexual violence, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"MN",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/senate-bill/288",
                    u"bill_type": u"s",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116s288is/pdf/BILLS-116s288is.pdf",
                    u"primary_subject": u"Native Americans",
                    u"active": False,
                    u"committees": u"Senate Indian Affairs Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/s288.json",
                    u"latest_major_action": u"Read twice and referred to the Committee on Indian Affairs.",
                    u"sponsor_title": u"Sen.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/S001203.json",
                    u"committee_codes": [u"SLIA"],
                    u"short_title": u"Justice for Native Survivors of Sexual Violence Act",
                    u"introduced_date": u"2019-01-31",
                    u"latest_major_action_date": u"2019-01-31",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/s288",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"s288",
                    u"cosponsors": 2,
                    u"bill_id": u"s288-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Rosa DeLauro",
                    u"number": u"H.R.7",
                    u"house_passage": None,
                    u"sponsor_id": u"D000216",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 1, u"D": 238},
                    u"vetoed": None,
                    u"title": u"To amend the Fair Labor Standards Act of 1938 to provide more effective remedies to victims of discrimination in the payment of wages on the basis of sex, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"CT",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/7",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr7ih/pdf/BILLS-116hr7ih.pdf",
                    u"primary_subject": u"Labor and Employment",
                    u"active": False,
                    u"committees": u"House Education and Labor",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr7.json",
                    u"latest_major_action": u"Referred to the House Committee on Education and Labor.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/D000216.json",
                    u"committee_codes": [u"HSED"],
                    u"short_title": u"Paycheck Fairness Act",
                    u"introduced_date": u"2019-01-30",
                    u"latest_major_action_date": u"2019-01-30",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr7",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr7",
                    u"cosponsors": 239,
                    u"bill_id": u"hr7-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Susan A. Davis",
                    u"number": u"H.R.874",
                    u"house_passage": None,
                    u"sponsor_id": u"D000598",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"R": 3, u"D": 34},
                    u"vetoed": None,
                    u"title": u"To amend title 28, United States Code, to prohibit the exclusion of individuals from service on a Federal jury on account of sexual orientation or gender identity.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"CA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/house-bill/874",
                    u"bill_type": u"hr",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116hr874ih/pdf/BILLS-116hr874ih.pdf",
                    u"primary_subject": u"Law",
                    u"active": False,
                    u"committees": u"House Judiciary Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/hr874.json",
                    u"latest_major_action": u"Referred to the House Committee on the Judiciary.",
                    u"sponsor_title": u"Rep.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/D000598.json",
                    u"committee_codes": [u"HSJU"],
                    u"short_title": u"Juror Non-Discrimination Act of 2019",
                    u"introduced_date": u"2019-01-30",
                    u"latest_major_action_date": u"2019-01-30",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/hr874",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"hr874",
                    u"cosponsors": 37,
                    u"bill_id": u"hr874-116",
                },
                {
                    u"senate_passage": None,
                    u"sponsor_name": u"Patty Murray",
                    u"number": u"S.270",
                    u"house_passage": None,
                    u"sponsor_id": u"M001111",
                    u"sponsor_party": u"D",
                    u"summary": u"",
                    u"cosponsors_by_party": {u"D": 44, u"ID": 1},
                    u"vetoed": None,
                    u"title": u"A bill to amend the Fair Labor Standards Act of 1938 to provide more effective remedies to victims of discrimination in the payment of wages on the basis of sex, and for other purposes.",
                    u"summary_short": u"",
                    u"last_vote": None,
                    u"sponsor_state": u"WA",
                    u"congressdotgov_url": u"https://www.congress.gov/bill/116th-congress/senate-bill/270",
                    u"bill_type": u"s",
                    u"gpo_pdf_uri": u"https://www.govinfo.gov/content/pkg/BILLS-116s270is/pdf/BILLS-116s270is.pdf",
                    u"primary_subject": u"Labor and Employment",
                    u"active": False,
                    u"committees": u"Senate Health, Education, Labor, and Pensions Committee",
                    u"enacted": None,
                    u"bill_uri": u"https://api.propublica.org/congress/v1/116/bills/s270.json",
                    u"latest_major_action": u"Read twice and referred to the Committee on Health, Education, Labor, and Pensions.",
                    u"sponsor_title": u"Sen.",
                    u"sponsor_uri": u"https://api.propublica.org/congress/v1/members/M001111.json",
                    u"committee_codes": [u"SSHR"],
                    u"short_title": u"Paycheck Fairness Act",
                    u"introduced_date": u"2019-01-30",
                    u"latest_major_action_date": u"2019-01-30",
                    u"govtrack_url": u"https://www.govtrack.us/congress/bills/116/s270",
                    u"subcommittee_codes": [],
                    u"bill_slug": u"s270",
                    u"cosponsors": 45,
                    u"bill_id": u"s270-116",
                },
            ],
            u"num_results": 20,
            u"offset": 0,
        }
    ],
    u"copyright": u"Copyright (c) 2019 Pro Publica Inc. All Rights Reserved.",
}
