<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-09-28 08:43
=======
# Generated by Django 3.2.7 on 2021-09-27 09:25
>>>>>>> f693e3c878920b2ff58c282b4f88f507b61bf985

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('accounts', '0004_auto_20210914_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(related_name='user_categories', to='categories.Category'),
        ),
    ]
