# Generated by Django 3.2.8 on 2021-10-30 11:48

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.PathAndRename('profile_uploads')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.PathAndRename('profile_uploads')),
        ),
    ]
