# Generated by Django 4.1.2 on 2022-10-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20211030_1148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                related_name="followers", to="accounts.profile"
            ),
        ),
    ]
