# Generated by Django 4.1.2 on 2022-10-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_profile_followers_alter_profile_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="full_profile",
        ),
    ]
