# Generated by Django 3.2.7 on 2021-10-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
        ('accounts', '0005_alter_profile_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('new_follower', 'New follower'), ('response_to_yout_civi', 'Response to your civi'), ('rebuttal_to_your_response', 'Rebuttal to your response')], default='new_follower', max_length=31)),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.profile')),
                ('civi', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='threads.civi')),
                ('thread', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='threads.thread')),
            ],
        ),
    ]
