# dev settings
# CIVIWIKI_DEV_HOST
# CIVIWIKI_DEV_PORT
# CIVIWIKI_DEV_NAME
# CIVIWIKI_DEV_ENGINE
# CIVIWIKI_DEV_USERNAME
# CIVIWIKI_DEV_PASSWORD

# local settings
# CIVIWIKI_LOCAL_NAME
# CIVIWIKI_LOCAL_USERNAME
# CIVIWIKI_LOCAL_PASSWORD

# production settings
# RDS_DB_NAME
# RDS_PORT
# RDS_USERNAME
# RDS_PASSWORD
